
const List<Map<String, Object>> categories = [

  {
    "id":"1",
    "title":"samsung",
    "price":"8000",
    "images":"assets/images/Apple-iPhone-11-PNG-Image.png"
  },
  {
    "id":"2",
    "title":"iphone",
    "price":"50000",
    "images":"assets/images/Apple-iPhone-11-PNG-Pic.png"
  },
  {
    "id":"3",
    "title":"realme",
    "price":"15000",
    "images":"assets/images/Apple-iPhone-11-Transparent-PNG.png"
  },
  {
    "id":"4",
    "title":"moto",
    "price":"20000",
    "images":"assets/images/Apple-iPhone-11-Transparent-PNG.png"
  },
  {
    "id":"5",
    "title":"Redmi",
    "price":"12000",
    "images":"assets/images/Apple-iPhone-12-PNG-Image.png"
  },
  {
    "id":"6",
    "title":"Nokia",
    "price":"6000",
    "images":"assets/images/Apple-iPhone-12-PNG-Photo.png"
  },
  {
    "id":"7",
    "title":"micromax",
    "price":"5000",
    "images":"assets/images/Apple-iPhone-12-Transparent-Images-PNG.png"
  },
  {
    "id":"8",
    "title":"IQ",
    "price":"25000",
    "images":"assets/images/Apple-iPhone-12-PNG-Photo.png"
  },
  {
    "id":"9",
    "title":"Htc",
    "price":"20000",
    "images":"assets/images/Mobile-Phone-Transparent-PNG.png"
  },
  {
    "id":"10",
    "title":"china",
    "price":"50000",
    "images":"assets/images/Mobile-Phone-PNG-HD.png"
  },
];